/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-12-03 03:48:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ThanhToan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Code/Eclip/DoAnLapTop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteLapTop/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1633527551849L));
    _jspx_dependants.put("jar:file:/D:/Code/Eclip/DoAnLapTop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteLapTop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vn\">\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("header .container .content_header .card_header .card {\r\n");
      out.write("	background-color: rgb(98, 217, 238);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header .container .content_header .card_header .card .logoutx {\r\n");
      out.write("	width: 8vw; <!-- ---- --> . modal { display : none;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	padding-top: 100px;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("	background-color: rgb(0, 0, 0);\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	function myFunction() {\r\n");
      out.write("		alert(\"Mua Hàng Thành Công\");\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"\r\n");
      out.write("	integrity=\"sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("<script src=\"html2pdf.bundle.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js\"></script>\r\n");
      out.write("<title>Thanh Toán</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("	<section class=\"top\">\r\n");
      out.write("		<header class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h1>Thông Tin Người Nhận</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("	</section>\r\n");
      out.write("	<section class=\"menu-login\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-7\">\r\n");
      out.write("					<form action=\"ThanhToanServlet\" method=\"post\">\r\n");
      out.write("						<!-- Ten nguoi -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"firstlastname\">Họ Và Tên Người Nhận:</label> <input\r\n");
      out.write("								type=\"text\" id=\"firstlastname\" name=\"firstlastname\"\r\n");
      out.write("								class=\"form-control\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Ten TK -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"username\">User Name:</label> <input type=\"text\"\r\n");
      out.write("								id=\"username\" name=\"username\" class=\"form-control\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Địa Chỉ -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"diachi\">Địa Chỉ:</label> <input type=\"text\"\r\n");
      out.write("								id=\"diachi\" name=\"diachi\" class=\"form-control\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Number Phone -->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"numberphone\">Số Điện Thoại:</label> <input\r\n");
      out.write("								type=\"text\" id=\"numberphone\" name=\"numberphone\"\r\n");
      out.write("								class=\"form-control\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Gioi Tinh-->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"genderM\">Gender:</label>\r\n");
      out.write("							<div class=\"form-check form-check-inline\">\r\n");
      out.write("								<input type=\"radio\" id=\"genderM\" name=\"genderM\"\r\n");
      out.write("									class=\"form-check-input\" /> <label for=\"genderM\">Male</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-check form-check-inline\">\r\n");
      out.write("								<input type=\"radio\" id=\"genderF\" name=\"genderF\"\r\n");
      out.write("									class=\"form-check-input\" /> <label for=\"genderF\">Female</label>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Quoc Tich-->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"nationality\">Quốc Tịch:</label> <select\r\n");
      out.write("								name=\"nationality\" id=\"nationality\" data-live-search=\"true\"\r\n");
      out.write("								class=\"form-control selectpicker\">\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"VietNam\">VietNam</option>\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"Jpan\">Jpan</option>\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"China\">\"China\"</option>\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"korean\">korean</option>\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"Campuchia\">Campuchia</option>\r\n");
      out.write("								<option data-tokens=\"Asian\" value=\"Indonesia\">Indonesia</option>\r\n");
      out.write("								<option data-tokens=\"Europe\" value=\"England\">England</option>\r\n");
      out.write("								<option data-tokens=\"Europe\" value=\"Paris\">Philippines</option>\r\n");
      out.write("								<option data-tokens=\"Europe\" value=\"American\">American</option>\r\n");
      out.write("								<option data-tokens=\"Europe\" value=\"Russia\">Russia</option>\r\n");
      out.write("							</select>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<!--Ghi Chu-->\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"noted\">noted</label>\r\n");
      out.write("							<textarea name=\"noted\" id=\"noted\" rows=\"3\" class=\"form-control\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<hr />\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-5\">\r\n");
      out.write("					<h3>Xác Nhận Thông Tin Người Nhận</h3>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>Họ và Tên: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${firstlastname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("						<li>Địa Chỉ: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${diachi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("						<li>numberphone: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberphone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("						<li>Gender: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("						<li>Nationality: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nationality }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("						<li>Noted: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noted }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<button id=\"cart\">xác nhận</button>\r\n");
      out.write("					<div id=\"myModal\" class=\"modal\"\r\n");
      out.write("						style=\"width: 40%; margin-left: 30%;\">\r\n");
      out.write("						<div id=\"area-print\" class=\"modal-content\"\r\n");
      out.write("							style=\"background: #e1f9fb;\">\r\n");
      out.write("							<div class=\"modal-header\">\r\n");
      out.write("								<h5 style=\"margin-left: 30%; color: red; font-size: 200%;\"\r\n");
      out.write("									class=\"modal-title\">Hóa đơn</h5>\r\n");
      out.write("								<span class=\"close\">&times;</span>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">Họ và Tên:\r\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${firstlastname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">Địa Chỉ: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${diachi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">numberphone:\r\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numberphone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">Gender: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">Nationality:\r\n");
      out.write("								");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nationality }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("							<p style=\"margin: 0px 0px 0px 20px\">Noted: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noted }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"modal-body\">\r\n");
      out.write("								\r\n");
      out.write("								<table border=1>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>Tên Sản Phẩm</th>\r\n");
      out.write("										<th>Giá Sản Phẩm</th>\r\n");
      out.write("										<th>Số Lượng</th>\r\n");
      out.write("										<th>Tổng Tiền</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</table>\r\n");
      out.write("								<div class=\"cart-total\">\r\n");
      out.write("									<strong class=\"cart-total-title\">Tổng Cộng:\r\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongtien}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong> <span class=\"cart-total-price\">VNĐ</span><br /> <strong\r\n");
      out.write("										class=\"cart-total-title\">Tổng Số Lượng: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${soluong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong> <span\r\n");
      out.write("										class=\"cart-total-price\">Cái</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"modal-footer\">\r\n");
      out.write("								<div class=\"col\">\r\n");
      out.write("									<h3 class=\"name_website\" style=\"font-size: 1rem\">Blue\r\n");
      out.write("										Laptop</h3>\r\n");
      out.write("									<div>\r\n");
      out.write("										<img src=\"");
      out.print(request.getContextPath());
      out.write("/upload/logone1.png\"\r\n");
      out.write("											alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"copyriht\"\r\n");
      out.write("										style=\"text-align: center; margin-bottom: -10px;\">Website\r\n");
      out.write("										design By @Team3</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary close-footer\">Đóng</button>\r\n");
      out.write("						<input class=\"btn btn-secondary close-footer\" style=\"background-color:green\" type=\"button\" id=\"btn-print\"\r\n");
      out.write("							value=\"Xuất hóa đơn\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"\r\n");
      out.write("		integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		// Modal\r\n");
      out.write("		var modal = document.getElementById(\"myModal\");\r\n");
      out.write("		var btn = document.getElementById(\"cart\");\r\n");
      out.write("		var close = document.getElementsByClassName(\"close\")[0];\r\n");
      out.write("		/* tại sao lại có [0] như  thế này bởi vì mỗi close là một html colection nên khi mình muốn lấy giá trị html thì phải thêm [0]. \r\n");
      out.write("		Nếu mình có 2 cái component cùng class thì khi [0] nó sẽ hiển thị component 1 còn [1] thì nó sẽ hiển thị component 2. */\r\n");
      out.write("		var close_footer = document.getElementsByClassName(\"close-footer\")[0];\r\n");
      out.write("		var order = document.getElementsByClassName(\"order\")[0];\r\n");
      out.write("		btn.onclick = function() {\r\n");
      out.write("			modal.style.display = \"block\";\r\n");
      out.write("		}\r\n");
      out.write("		close.onclick = function() {\r\n");
      out.write("			modal.style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("		close_footer.onclick = function() {\r\n");
      out.write("			modal.style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("		order.onclick = function() {\r\n");
      out.write("			alert(\"Cảm ơn bạn đã thanh toán đơn hàng\")\r\n");
      out.write("		}\r\n");
      out.write("		window.onclick = function(event) {\r\n");
      out.write("			if (event.target == modal) {\r\n");
      out.write("				modal.style.display = \"none\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document)\r\n");
      out.write("				.ready(\r\n");
      out.write("						function() {\r\n");
      out.write("							var area_print = $('#area-print');\r\n");
      out.write("							var cache_width = area_print.width();\r\n");
      out.write("							var a4 = [ 595.28, 841.89 ];\r\n");
      out.write("							$('#btn-print').on('click', function() {\r\n");
      out.write("								createPDF();\r\n");
      out.write("							});\r\n");
      out.write("							function createPDF() {\r\n");
      out.write("								getCanvas()\r\n");
      out.write("										.then(\r\n");
      out.write("												function(canvas) {\r\n");
      out.write("													var img = canvas\r\n");
      out.write("															.toDataURL(\"image/png\"), doc = new jsPDF(\r\n");
      out.write("															{\r\n");
      out.write("																unit : 'px',\r\n");
      out.write("																format : 'a4'\r\n");
      out.write("															});\r\n");
      out.write("													doc.addImage(img, 'JPEG',\r\n");
      out.write("															20, 20);\r\n");
      out.write("													doc\r\n");
      out.write("															.save('convert_html_to_pdf.pdf');\r\n");
      out.write("													area_print\r\n");
      out.write("															.width(cache_width);\r\n");
      out.write("												});\r\n");
      out.write("								// create canvas object  \r\n");
      out.write("								function getCanvas() {\r\n");
      out.write("									area_print.width((a4[0] * 1.33333) - 80)\r\n");
      out.write("											.css('max-width', 'none');\r\n");
      out.write("									return html2canvas(area_print, {\r\n");
      out.write("										imageTimeout : 2000,\r\n");
      out.write("										removeContainer : true\r\n");
      out.write("									});\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/ThanhToan.jsp(168,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/ThanhToan.jsp(168,9) '${listGioHang}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listGioHang}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /views/ThanhToan.jsp(168,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("sp");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										<tr>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.tenSP}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.giaSP}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("VNĐ</td>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.soLuong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.soLuong * sp.giaSP}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("VNĐ</td>\r\n");
            out.write("										</tr>\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
