/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.50
 * Generated at: 2021-12-01 19:29:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.viewsnhanvien;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class InsertThongTinSanPhamDB_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/Code/Eclip/DoAnLapTop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteLapTop/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1633527551849L));
    _jspx_dependants.put("jar:file:/D:/Code/Eclip/DoAnLapTop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebsiteLapTop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vn\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Thêm Thông Tin Sản Phẩm</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/SanPham.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".show input {\r\n");
      out.write("	width: 40%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".show textarea {\r\n");
      out.write("	width: 40%;\r\n");
      out.write("	height: 10vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".show button {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("	height: 4vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menunv {\r\n");
      out.write("	margin: 1px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 16%;\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	min-height: 500px;\r\n");
      out.write("	 background: #000055;\r\n");
      out.write("	height: 100vh\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Next and Previous */\r\n");
      out.write(".nextprevious {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 8px 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nextprevious:hover {\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".previous {\r\n");
      out.write("	background-color: #f1f1f1;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".next {\r\n");
      out.write("	background-color: #04AA6D;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".round {\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nextpreviouscancel {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 8px 16px;\r\n");
      out.write("	opacity: 0.5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nextpreviouscacel:hover {\r\n");
      out.write("	background-color: #ddd;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".show_product table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("\r\n");
      out.write("	/js/SanPham.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<div class=\"headernv\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/viewsnhanvien/Header.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"menunv\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/viewsnhanvien/Menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("	<form action=\"InsertThongTinSanPhamDB\" method=\"post\">\r\n");
      out.write("		<section class=\"body_product\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"title\">\r\n");
      out.write("					<h3>Thêm Thông Tin Sản Phẩm</h3>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"show\">\r\n");
      out.write("\r\n");
      out.write("					<label for=\"TenSP\">Tên Sản Phẩm:</label> <br /> <input type=\"text\"\r\n");
      out.write("						id=\"TenSP\" name=\"TenSP\" class=\"form-control\"> <br />\r\n");
      out.write("					<br />\r\n");
      out.write("					<br /> <label for=\"GiaSP\">Giá Sản Phẩm:</label> <br />\r\n");
      out.write("					<input type=\"text\" id=\"GiaSP\" name=\"GiaSP\" class=\"form-control\">\r\n");
      out.write("					<br />\r\n");
      out.write("					<br />\r\n");
      out.write("					<br /> <label for=\"ThoiGianBaoHanh\">Thời Gian Bảo Hành:</label> <br />\r\n");
      out.write("					<input type=\"text\" id=\"ThoiGianBaoHanh\" name=\"ThoiGianBaoHanh\"\r\n");
      out.write("						class=\"form-control\"> <br />\r\n");
      out.write("					<br />\r\n");
      out.write("					<br /> <label for=\"XuatXu\">Xuất Xứ:</label> <br />\r\n");
      out.write("					<input type=\"text\" id=\"XuatXu\" name=\"XuatXu\" class=\"form-control\">\r\n");
      out.write("					<br />\r\n");
      out.write("					<br />\r\n");
      out.write("					<br /> <label for=\"ThongSo\">Thông Số:</label> <br />\r\n");
      out.write("					<textarea id=\"ThongSo\" name=\"ThongSo\" class=\"form-control\"></textarea>\r\n");
      out.write("					<br />\r\n");
      out.write("					<br />\r\n");
      out.write("					<br /> <label for=\"SoLuongTon\">Số Lượng Tồn:</label> <br />\r\n");
      out.write("					<input type=\"text\" id=\"SoLuongTon\" name=\"SoLuongTon\"\r\n");
      out.write("						class=\"form-control\"> <br /> <br /> <br />\r\n");
      out.write("					\r\n");
      out.write("					<button style=\"background-color: springgreen;\" type=\"submit\">Thêm</button>\r\n");
      out.write("					<button type=\"reset\">Reset</button><br />\r\n");
      out.write("					<a href=\"ThongTinSanPhamDB\">Return List ThongTinSanPham</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- end Body product discount -->\r\n");
      out.write("\r\n");
      out.write("		<script src=\"https://kit.fontawesome.com/03bca92048.js\"\r\n");
      out.write("			crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
